language: python
jobs:
  include:
  - name: Python 3.8.0 on Xenial Linux
    python: 3.8
  - name: Python 3.6.10 on FreeBSD
    os: freebsd
    language: python
  - name: Python 3.7.4 on macOS
    os: osx
    osx_image: xcode11.2
    language: shell
  - name: Python 3.8.0 on Windows
    os: windows
    language: shell
    before_install:
    - openssl aes-256-cbc -K $encrypted_76dee02f3458_key -iv $encrypted_76dee02f3458_iv
      -in dialogflow_key.json.enc -out dialogflow_key.json -d
    - choco install python --version 3.8.0
    - python -m pip install --upgrade pip
    env: 
    - GOOGLE_APPLICATION_CREDENTIALS=env/dialogflow_key.json
    - PATH=/c/Python38:/c/Python38/Scripts:$PATH
before_install:
- openssl aes-256-cbc -K $encrypted_76dee02f3458_key -iv $encrypted_76dee02f3458_iv
  -in dialogflow_key.json.enc -out dialogflow_key.json -d
- pip3 install --upgrade pip
env:
- GOOGLE_APPLICATION_CREDENTIALS=dialogflow_key.json
install:
- pip install -r requirements.txt
script: pytest
